// This file was autogenerated by gulp-closure-deps plugin.
// Please do not edit.
goog.addDependency('../../../../src/momentum/Coordinate.js', ['momentum.Coordinate'], [], false);
goog.addDependency('../../../../src/momentum/Draggable.js', ['momentum.Draggable'], ['momentum.Coordinate', 'momentum.Handler', 'momentum.HandlerComponent', 'momentum.utils'], false);
goog.addDependency('../../../../src/momentum/Handler.js', ['momentum.Handler'], ['momentum.Coordinate', 'momentum.TrackingPoint', 'momentum.utils'], false);
goog.addDependency('../../../../src/momentum/HandlerComponent.js', ['momentum.HandlerComponent'], [], false);
goog.addDependency('../../../../src/momentum/Rotatable.js', ['momentum.Rotatable'], ['momentum.Handler', 'momentum.HandlerComponent', 'momentum.utils'], false);
goog.addDependency('../../../../src/momentum/TrackingPoint.js', ['momentum.TrackingPoint'], ['momentum.Coordinate'], false);
goog.addDependency('../../../../src/momentum/index.js', ['momentum'], ['momentum.Draggable', 'momentum.Handler', 'momentum.Rotatable'], false);
goog.addDependency('../../../../src/momentum/utils.js', ['momentum.utils'], ['goog.dom', 'momentum.Coordinate'], false);
goog.addDependency('../../../../src/momentumdebug/Configurator.js', ['momentumdebug.Configurator'], ['momentum.Draggable', 'momentum.utils', 'momentumdebug.ScriptLoader'], false);
goog.addDependency('../../../../src/momentumdebug/ScriptLoader.js', ['momentumdebug.ScriptLoader'], [], false);
goog.addDependency('../../../../src/momentumdebug/index.js', ['momentumdebug'], ['momentum', 'momentumdebug.Configurator'], false);